import snakemake 
import os
import re

samples: list[str] = [
    "Sample1", 
    "Sample2", 
    "Sample3"
]

# Rule 'all', defining all requested output.
rule all:
    input: 
        expand("output/data/{sample}_R1.clean.fastq", sample = samples),
        expand("output/data/{sample}_R2.clean.fastq", sample = samples)

# Rule 'fastp' preprocesses the reads by detecting and removing adapters,
# filtering reads with an average quality less than 20, and producing 
# filtered fastq reads with preprocessing reports.
rule fastp: 
    input:
        r1 = "../data/{sample}_R1.fastq",
        r2 = "../data/{sample}_R2.fastq"
    output:
        r1_clean = "output/data/{sample}_R1.clean.fastq",
        r2_clean = "output/data/{sample}_R2.clean.fastq",
        html_report = "output/reports/{sample}-fastp-report.html",
        json_report = "output/reports/{sample}-fastp-report.json"
    shell:
        """
        fastp --in1 {input.r1} --in2 {input.r2} \
        --out1 {output.r1_clean} --out2 {output.r2_clean} \
        --detect_adapter_for_pe \
        --average_qual 20 \
        --html {output.html_report} \
        --json {output.json_report}
        """